/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 earth.glb
Author: Javier Da Rosa (https://sketchfab.com/Javier_Da_Rosa)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/earth-shine-e2127cd69e04473bb7728f2a579d6089
Title: Earth Shine
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function EarthModel(props) {
    const { nodes, materials } = useGLTF('/models/earth.glb')
    return (
        <group {...props} dispose={null} scale={1}>
            <mesh geometry={nodes.Object_2.geometry} material={materials.wire_000000000} rotation={[-Math.PI / 2, 0, 0]} />
        </group>
    )
}

useGLTF.preload('/models/earth.glb')
