/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 globe.glb
Author: Ep Digital Design (https://sketchfab.com/Epdigitaldesign)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/wireframe-3d-globe-20adb20e73ee4b68bc1207e1675b8891
Title: Wireframe 3D Globe
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function GlobeObject(props) {
    const { nodes, materials } = useGLTF('/models/globe.glb')
    return (
        <group {...props} dispose={null} scale={0.04}>
            <mesh geometry={nodes.Object_2.geometry} material={materials['Material.001']} rotation={[Math.PI / 2, 0, -Math.PI]} />
        </group>
    )
}

useGLTF.preload('/models/globe.glb')
